import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { api } from "../api";

/**
 * "In plain English" panel — drop at the end of each section.
 *
 * Two modes:
 *   - <LaymanExplanation section="leaderboard" />        ← Claude-generated, dynamic
 *   - <LaymanExplanation>...static text...</LaymanExplanation>  ← fallback
 */
export default function LaymanExplanation({
  children,
  section,
  title = "IN PLAIN ENGLISH",
}: {
  children?: ReactNode;
  section?: string;
  title?: string;
}) {
  const [text, setText] = useState<string | null>(null);
  const [source, setSource] = useState<string>("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!section) return;
    setLoading(true);
    api.explain(section)
      .then(r => { setText(r.text); setSource(r.source); })
      .catch(() => { setText(null); setSource("error"); })
      .finally(() => setLoading(false));
  }, [section]);

  const showStatic = !section || (text === null && !loading);
  const sourceTag = source === "claude"   ? "Claude Sonnet 4.6"
                  : source === "fallback" ? "static fallback"
                  : "";

  return (
    <div className="mt-5 rounded-lg border-l-4 border-emerald-500/60 bg-emerald-950/20 px-5 py-4">
      <div className="text-emerald-400 text-[10px] font-bold tracking-[0.25em] mb-2 flex items-center justify-between">
        <span className="flex items-center gap-2">
          <span>💡</span>
          <span>{title}</span>
        </span>
        {sourceTag && (
          <span className="text-zinc-600 text-[9px] tracking-[0.2em] font-normal italic">
            generated by {sourceTag}
          </span>
        )}
      </div>
      <div className="text-zinc-300 text-sm leading-relaxed">
        {loading && (
          <span className="text-zinc-500 italic">
            Asking Claude to explain this section…
          </span>
        )}
        {!loading && section && text && <span>{text}</span>}
        {showStatic && children}
      </div>
    </div>
  );
}
